# Generated by Django 5.2.10 on 2026-02-07 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrule',
            options={'verbose_name': 'Правило доступа', 'verbose_name_plural': 'Правила доступа'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Разрешение', 'verbose_name_plural': 'Разрешения'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Ресурс', 'verbose_name_plural': 'Ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Пользовательская роль', 'verbose_name_plural': 'Пользовательские роли'},
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='Резрешено'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.permission', verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.resource', verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=100, verbose_name='Хэш пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
