# Generated by Django 5.2.10 on 2026-02-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_accessrule_options_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.resource', verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='Разрешено'),
        ),
    ]
