# Generated by Django 5.2.10 on 2026-02-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_permission_resource_alter_accessrule_is_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='resource',
        ),
    ]
